org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 --enable-native-access=ALL-UNNAMED
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false

# Fix Windows cross-drive Kotlin incremental compilation bug (C: Pub Cache vs D: Workspace)
kotlin.incremental=false
kotlin.incremental.multiplatform=false
kotlin.compiler.execution.strategy=in-process
